# Findings and Observations - Wireshark Traffic Analysis

## Overview
This document summarizes the key observations from the live network capture using Wireshark on Windows. The captured `.pcapng` file includes traffic generated by web browsing, ICMP pings, and typical system background processes. The focus is on analyzing packet flow, identifying protocols, and recognizing interesting behaviors.

---

## Protocols Observed

### 1. ICMP (Ping Requests and Replies)
- **Observation:** Several ICMP Echo Requests were sent to `8.8.8.8` and corresponding Echo Replies were received.
- **Packet Size:** 74 bytes typical for ping.
- **Insight:** Round Trip Time (RTT) averaged around X ms (if measured). No packet loss observed in the trace.
- **TTL (Time-To-Live):** Most replies had TTL ≈ 118–120, suggesting the server was ~10 hops away.

---

### 2. DNS (Domain Name System)
- **Observation:** Multiple DNS queries to resolve domain names such as `www.google.com`, `clients3.google.com`, etc.
- **Insight:** Both A (IPv4) and AAAA (IPv6) queries were seen.
- **Behavior:** DNS queries went to the local router or ISP DNS (e.g., `192.168.X.X`) and received timely responses.
- **Interesting:** DNS uses UDP port 53, but fallback to TCP was not observed (no truncated flags set).

---

### 3. HTTP
- **Observation:** HTTP GET requests to websites such as `example.com` and possible redirects.
- **Insight:** Plaintext content type headers visible in some packets.
- **Interesting Note:** No HTTPS (SSL/TLS) packets were seen in this session — either HTTPS traffic was minimal or filtered out.

---

## Additional Observations

- **Packet Flags & Flow:**
  - TCP handshakes (SYN, SYN-ACK, ACK) observed for some connections.
  - No signs of TCP retransmissions, out-of-order segments, or RST packets.

- **No Malware/Anomaly Detected:**  
  The capture appeared clean with normal web and system communication behavior. No suspicious IPs, unknown protocols, or data exfiltration patterns were seen.

- **Broadcast Packets:**  
  ARP and MDNS (Multicast DNS) seen occasionally — common in local Windows network discovery.

---

## Conclusion

This analysis confirms a functional and secure network environment with visible use of standard protocols like ICMP, DNS, and HTTP. Wireshark effectively captured live traffic, and deeper inspection shows stable, consistent communication with no apparent errors or malicious activity.

